version: '3'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/vol
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/app/static:/www/static

  data:
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  data-volume:
