version: '3'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/vol
    env_file: .env
    command: /usr/local/bin/gunicorn --reload -w 2 -b :8000 app:app --log-level=debug

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/app/static:/www/static

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .db_env

  gulper:
    restart: always
    build: ./gulper
    volumes:
      - ./web:/runtime/src

  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./redis-data:/mounting-data
    command: redis-server --dbfilename dump.rdb --dir /mounting-data
    ports:
      - "6379:6379"

volumes:
  data-volume:
