version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: vol/.env
    depends_on:
      - db
    volumes:
      - ./vol:/vol
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
